# -*- coding: utf-8 -*-
"""LINEAR REGRESSION 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KW81NKtc903dxQhcRM41_fkUIk0VAt43

import libraries
"""

import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""load dataset"""

df = pd.read_csv("/content/Housing_enriched_cleaned (1).csv")

print(df.head())
print(df.shape)

"""EDA"""

print(df.info())

print(df.describe())

print(df.isnull().sum())

print(df.duplicated().sum())

"""dATA CLEANING"""

# Remove Duplicate Records
df.drop_duplicates(inplace=True)

# Separate Numerical and Categorical Columns
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Handle Missing Values
num_imputer = SimpleImputer(strategy='median')
cat_imputer = SimpleImputer(strategy='most_frequent')

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

print("Missing Values After Cleaning")
print(df.isnull().sum())

"""DATA PREPROCESSING"""

encoder = LabelEncoder()

for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

print(df.head())

"""FEATURE ENGNEERING"""

encoder = LabelEncoder()

for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

print(df.head())

"""FEATURE SCALING"""

y = df['price']
X = df.drop('price', axis=1)

scaler = StandardScaler()

X = scaler.fit_transform(X)

"""SPLIT DATASET"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

"""MODEL"""

model = LinearRegression()

"""TRAIN MODEL"""

model.fit(X_train, y_train)

print("Training Completed")

"""PREDICTION"""

y_pred = model.predict(X_test)

print(y_pred[:10])

"""MODEL EVALUATION"""

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

mape = np.mean(np.abs((y_test-y_pred)/y_test))*100

accuracy = 100-mape

print("MAE :",mae)
print("MSE :",mse)
print("RMSE :",rmse)
print("R2 Score :",r2)
print("MAPE :",mape,"%")
print("Accuracy :",accuracy,"%")

"""FEATURE IMPORTANCE"""

importance = pd.DataFrame({
    "Feature":df.drop("price",axis=1).columns,
    "Coefficient":model.coef_
})

importance["Absolute Importance"] = abs(importance["Coefficient"])

importance = importance.sort_values(
    by="Absolute Importance",
    ascending=False
)

print(importance)

"""PREDICT NEW PROPERTY"""

sample = X_test[0:1]

prediction = model.predict(sample)

print("Predicted Property Value :",prediction[0])

"""SAVE MODEL"""

joblib.dump(model,"Property_Valuation_Model.pkl")

joblib.dump(scaler,"Scaler.pkl")

print("Model Saved Successfully")

"""ACTUAL VS PREDICTED"""

comparison = pd.DataFrame({
    "Actual Price":y_test.values,
    "Predicted Price":y_pred
})

print(comparison.head(10))

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred, alpha=0.7)

# Perfect prediction reference line
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--',
    linewidth=2,
    label='Perfect Prediction'
)

plt.title("Actual vs Predicted Property Prices")
plt.xlabel("Actual Property Price")
plt.ylabel("Predicted Property Price")
plt.legend()
plt.grid(True)

plt.show()