# -*- coding: utf-8 -*-
"""GRADIENT BOOSTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gN_kujk91lRQKUbST5T0RIsr3IokpOMa

IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import matplotlib.pyplot as plt

"""LOAD DATASET"""

# Load dataset
df = pd.read_csv("Housing_enriched_cleaned (1).csv")

# Display first 5 rows
print(df.head())

# Shape of dataset
print("\nDataset Shape:")
print(df.shape)

# Dataset information
print("\nDataset Information:")
print(df.info())

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Statistical Summary
print("\nStatistical Summary:")
print(df.describe())

# Data types
print("\nData Types:")
print(df.dtypes)

"""SEPARATE FEATURES"""

X = df.drop("price", axis=1)
y = df["price"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

"""NUMERIC & CATEG COLUMNS"""

categorical_features = X.select_dtypes(include=['object']).columns

numerical_features = X.select_dtypes(
    exclude=['object']
).columns

print("Categorical Features:")
print(categorical_features)

print("\nNumerical Features:")
print(numerical_features)

"""PREPROCESSING"""

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

"""SPLIT DATASET"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples :", X_train.shape)
print("Testing Samples :", X_test.shape)

"""BULID MODEL"""

gbr = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", gbr)
])

model.fit(X_train, y_train)

print("Gradient Boosting Model Trained Successfully!")

"""PREDICTION

MODEL EVALUATION
"""

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Accuracy (R² as percentage)
accuracy = r2 * 100

print("\nGradient Boosting Model Evaluation")
print("=" * 40)

print(f"Mean Absolute Error (MAE)      : {mae:.2f}")
print(f"Mean Squared Error (MSE)       : {mse:.2f}")
print(f"Root Mean Squared Error (RMSE) : {rmse:.2f}")
print(f"R² Score                       : {r2:.4f}")
print(f"Model Accuracy                 : {accuracy:.2f}%")

"""FEATURES IMPOTANCE"""

# Get trained regressor
regressor = model.named_steps["regressor"]

# Get feature names after encoding
encoded_names = model.named_steps[
    "preprocessor"
].get_feature_names_out()

# Feature importance
importance = pd.DataFrame({
    "Feature": encoded_names,
    "Importance": regressor.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance.head(20))

"""PLOT FEATURES

ACCURACY R
"""

accuracy = r2_score(y_test, y_pred) * 100

print(f"Gradient Boosting Accuracy: {accuracy:.2f}%")

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--',
    linewidth=2
)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted House Prices")

plt.show()