# -*- coding: utf-8 -*-
"""KNN CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FUwCRxEONZI68z9qtGV23bvDkzTxowm

import libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import matplotlib.pyplot as plt

"""load dataset"""

df = pd.read_csv("Housing_enriched_cleaned (1).csv")

print(df.head())

"""categorical to numeric"""

le = LabelEncoder()

categorical_columns = df.select_dtypes(include=['object']).columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

"""separate feature"""

X = df.drop("price", axis=1)

y = df["price"]

"""dataset"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""feature scale"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

"""train knn model"""

knn = KNeighborsRegressor(n_neighbors=5)

knn.fit(X_train, y_train)

"""predict value"""

y_pred = knn.predict(X_test)

"""evaluate model"""

ae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Convert R² to percentage (often informally called accuracy)
accuracy = r2 * 100

print("MAE :", ae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)
print("Accuracy :", accuracy, "%")

"""scatter plot"""

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")

plt.ylabel("Predicted Price")

plt.title("KNN Regression: Actual vs Predicted Price")

plt.show()

"""predict new house"""

sample = X.iloc[[0]]

sample = scaler.transform(sample)

prediction = knn.predict(sample)

print("Predicted House Price:", prediction[0])

"""scatter plot best fit"""

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual Price")

plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted Price")

plt.show()