# -*- coding: utf-8 -*-
"""Random forest(Rajesh).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tX62LeZTJe1Ixc3LPKw3OJew0SjVKDvS

LIBRARIES
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

"""Load the dataset"""

from google.colab import files

uploaded = files.upload()

df = pd.read_csv(r"/content/Housing_enriched_cleaned (1).csv")

df.head()

"""**EDA**"""

df.info()

df.shape

df.describe()

df.isnull().sum()

"""Data preprocessing"""

df = df.drop_duplicates()

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

num_imputer = SimpleImputer(strategy='median')
cat_imputer = SimpleImputer(strategy='most_frequent')

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

encoder = LabelEncoder()

for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

X = df.drop("price", axis=1)

y = df["price"]

"""Split dataset"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Random forest model"""

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""Evaluate model"""

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE :", rmse)
print("R2 Score :", r2)

accuracy = r2_score(y_test, y_pred) * 100

print("Model Accuracy: {:.2f}%".format(accuracy))

"""Feature importance"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print(importance)

"""Predict the property"""

sample = X.iloc[[0]]

prediction = model.predict(sample)

print("Predicted Property Price:", prediction[0])

"""Save the model"""

joblib.dump(model, "random_forest_property_model.pkl")

"""Visualization"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred, color='blue', alpha=0.6)

plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color='red', linewidth=2)

plt.title("Actual vs Predicted House Prices")
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")

plt.show()